// Question banks for the pub quiz. Each question carries the correct answer in
// `a` and three distractors in `wrong`; the UI shuffles them into 4 options.
// The "Player Round" is built at runtime from questions the players type in.
const GENERAL_ROUNDS = [
  {
    title: "Geography",
    description: "Places, capitals and landmarks.",
    questions: [
      { q: "What is the capital of Australia?", a: "Canberra", wrong: ["Sydney", "Melbourne", "Perth"] },
      { q: "Which country has the largest population in the world?", a: "India", wrong: ["China", "United States", "Indonesia"] },
      { q: "In which mountain range would you find Mount Everest?", a: "The Himalayas", wrong: ["The Andes", "The Alps", "The Rockies"] },
      { q: "Which African country was formerly known as Abyssinia?", a: "Ethiopia", wrong: ["Egypt", "Sudan", "Somalia"] },
      { q: "Which is the only sea on Earth with no coastline?", a: "The Sargasso Sea", wrong: ["The Dead Sea", "The Aral Sea", "The Baltic Sea"] },
      { q: "What is the smallest country in the world by area?", a: "Vatican City", wrong: ["Monaco", "Nauru", "San Marino"] },
      { q: "Which river flows through Paris?", a: "The Seine", wrong: ["The Loire", "The Rhône", "The Thames"] },
      { q: "On which continent is the Atacama Desert located?", a: "South America", wrong: ["Africa", "Asia", "Australia"] },
      { q: "Which ocean is the deepest?", a: "The Pacific Ocean", wrong: ["The Atlantic Ocean", "The Indian Ocean", "The Arctic Ocean"] },
      { q: "What is the capital of Canada?", a: "Ottawa", wrong: ["Toronto", "Vancouver", "Montreal"] },
      { q: "Which country is home to the ancient city of Petra?", a: "Jordan", wrong: ["Egypt", "Syria", "Iraq"] },
      { q: "The Strait of Gibraltar separates Europe from which continent?", a: "Africa", wrong: ["Asia", "North America", "Antarctica"] },
      { q: "Which is the largest country in the world by area?", a: "Russia", wrong: ["Canada", "China", "United States"] },
      { q: "What is the longest river in South America?", a: "The Amazon", wrong: ["The Paraná", "The Orinoco", "The São Francisco"] },
    ],
  },
  {
    title: "Science & Nature",
    description: "A little bit of biology, chemistry and physics.",
    questions: [
      { q: "What is the chemical symbol for gold?", a: "Au", wrong: ["Ag", "Go", "Gd"] },
      { q: "How many bones are in the adult human body?", a: "206", wrong: ["196", "216", "306"] },
      { q: "Which planet in our solar system is known as the Red Planet?", a: "Mars", wrong: ["Jupiter", "Venus", "Mercury"] },
      { q: "What is the hardest naturally occurring substance on Earth?", a: "Diamond", wrong: ["Quartz", "Granite", "Steel"] },
      { q: "What gas do plants primarily absorb for photosynthesis?", a: "Carbon dioxide (CO₂)", wrong: ["Oxygen", "Nitrogen", "Methane"] },
      { q: "What is the largest organ of the human body?", a: "The skin", wrong: ["The liver", "The lungs", "The intestines"] },
      { q: "Which element has the atomic number 1?", a: "Hydrogen", wrong: ["Helium", "Oxygen", "Carbon"] },
      { q: "Which blood type is known as the universal donor?", a: "O negative", wrong: ["O positive", "AB negative", "A positive"] },
      { q: "What does DNA stand for?", a: "Deoxyribonucleic acid", wrong: ["Dynamic Nucleic Acid", "Double Nuclear Acid", "Diribonucleic Acid"] },
      { q: "How many hearts does an octopus have?", a: "Three", wrong: ["One", "Two", "Eight"] },
      { q: "What force pulls objects toward the centre of the Earth?", a: "Gravity", wrong: ["Magnetism", "Friction", "Inertia"] },
      { q: "What is the boiling point of water at sea level in Celsius?", a: "100 °C", wrong: ["90 °C", "110 °C", "120 °C"] },
      { q: "What is the speed of light in a vacuum (to the nearest 1,000 km/s)?", a: "About 300,000 km/s", wrong: ["About 30,000 km/s", "About 3,000,000 km/s", "About 30,000,000 km/s"] },
      { q: "Which vitamin is produced by the body when exposed to sunlight?", a: "Vitamin D", wrong: ["Vitamin A", "Vitamin C", "Vitamin B12"] },
    ],
  },
  {
    title: "History",
    description: "Events and people from the past.",
    questions: [
      { q: "In what year did World War II end?", a: "1945", wrong: ["1944", "1946", "1939"] },
      { q: "Who was the first President of the United States?", a: "George Washington", wrong: ["Thomas Jefferson", "John Adams", "Abraham Lincoln"] },
      { q: "The Great Wall of China was primarily expanded under which dynasty?", a: "The Ming dynasty", wrong: ["The Qing dynasty", "The Han dynasty", "The Tang dynasty"] },
      { q: "Who painted the Mona Lisa?", a: "Leonardo da Vinci", wrong: ["Michelangelo", "Raphael", "Donatello"] },
      { q: "In which year did the Berlin Wall fall?", a: "1989", wrong: ["1987", "1990", "1991"] },
      { q: "Who was the first woman to win a Nobel Prize?", a: "Marie Curie", wrong: ["Rosa Parks", "Mother Teresa", "Florence Nightingale"] },
      { q: "Which civilization built Machu Picchu?", a: "The Inca", wrong: ["The Aztec", "The Maya", "The Olmec"] },
      { q: "Who wrote the play \"Romeo and Juliet\"?", a: "William Shakespeare", wrong: ["Christopher Marlowe", "Ben Jonson", "Geoffrey Chaucer"] },
      { q: "In what year did the Titanic sink?", a: "1912", wrong: ["1905", "1915", "1920"] },
      { q: "Which British Prime Minister was known as the \"Iron Lady\"?", a: "Margaret Thatcher", wrong: ["Theresa May", "Angela Merkel", "Golda Meir"] },
      { q: "Julius Caesar was a leader of which empire?", a: "The Roman Empire", wrong: ["The Byzantine Empire", "The Ottoman Empire", "Ancient Greece"] },
      { q: "Which country gifted the Statue of Liberty to the United States?", a: "France", wrong: ["Britain", "Spain", "Germany"] },
      { q: "Who was the first person to walk on the Moon?", a: "Neil Armstrong", wrong: ["Buzz Aldrin", "Yuri Gagarin", "Michael Collins"] },
      { q: "In what year did the French Revolution begin?", a: "1789", wrong: ["1776", "1799", "1815"] },
    ],
  },
  {
    title: "Entertainment",
    description: "Films, music, TV and books.",
    questions: [
      { q: "Who wrote the Harry Potter book series?", a: "J. K. Rowling", wrong: ["Stephen King", "Roald Dahl", "Philip Pullman"] },
      { q: "Which band released the 1969 album \"Abbey Road\"?", a: "The Beatles", wrong: ["The Rolling Stones", "The Who", "Pink Floyd"] },
      { q: "Who directed the original 1993 film \"Jurassic Park\"?", a: "Steven Spielberg", wrong: ["George Lucas", "James Cameron", "Ridley Scott"] },
      { q: "In which TV series would you hear the phrase \"Winter is coming\"?", a: "Game of Thrones", wrong: ["Breaking Bad", "The Witcher", "Vikings"] },
      { q: "Which Disney film features a snowman named Olaf?", a: "Frozen", wrong: ["Moana", "Tangled", "Brave"] },
      { q: "Who played Jack in the 1997 film \"Titanic\"?", a: "Leonardo DiCaprio", wrong: ["Brad Pitt", "Tom Cruise", "Matt Damon"] },
      { q: "Which musical features the song \"Defying Gravity\"?", a: "Wicked", wrong: ["Hamilton", "Les Misérables", "Chicago"] },
      { q: "What is the name of the wizarding school in Harry Potter?", a: "Hogwarts", wrong: ["Durmstrang", "Beauxbatons", "Ilvermorny"] },
      { q: "Who wrote \"The Lord of the Rings\"?", a: "J. R. R. Tolkien", wrong: ["C. S. Lewis", "George R. R. Martin", "Terry Pratchett"] },
      { q: "Which film won Best Picture at the 2020 Oscars?", a: "Parasite", wrong: ["1917", "Joker", "Once Upon a Time in Hollywood"] },
      { q: "Which artist painted \"The Starry Night\"?", a: "Vincent van Gogh", wrong: ["Claude Monet", "Paul Cézanne", "Pablo Picasso"] },
      { q: "What instrument did jazz legend Miles Davis play?", a: "Trumpet", wrong: ["Saxophone", "Piano", "Guitar"] },
      { q: "Who is the author of the James Bond novels?", a: "Ian Fleming", wrong: ["John le Carré", "Frederick Forsyth", "Tom Clancy"] },
      { q: "What colour pill does Neo take in \"The Matrix\"?", a: "Red", wrong: ["Blue", "Green", "Yellow"] },
    ],
  },
  {
    title: "Sports",
    description: "Teams, rules and record breakers.",
    questions: [
      { q: "How many players from one team are on the pitch in a standard football (soccer) match?", a: "11", wrong: ["9", "10", "12"] },
      { q: "In which sport would you use a shuttlecock?", a: "Badminton", wrong: ["Squash", "Table tennis", "Volleyball"] },
      { q: "Which country has won the most FIFA World Cups?", a: "Brazil (5)", wrong: ["Germany (4)", "Italy (4)", "Argentina (3)"] },
      { q: "What is the national sport of Japan?", a: "Sumo wrestling", wrong: ["Karate", "Judo", "Kendo"] },
      { q: "In tennis, what is a score of zero called?", a: "Love", wrong: ["Deuce", "Ace", "Nil"] },
      { q: "How many rings are on the Olympic flag?", a: "Five", wrong: ["Four", "Six", "Seven"] },
      { q: "In which sport is the Stanley Cup awarded?", a: "Ice hockey", wrong: ["American football", "Basketball", "Baseball"] },
      { q: "How often are the Summer Olympic Games held?", a: "Every four years", wrong: ["Every two years", "Every three years", "Every five years"] },
      { q: "What is the maximum score possible in a single game of ten-pin bowling?", a: "300", wrong: ["200", "250", "360"] },
      { q: "In which city were the 2016 Summer Olympics held?", a: "Rio de Janeiro", wrong: ["Tokyo", "London", "Beijing"] },
      { q: "How many players from one team are on a basketball court during play?", a: "5", wrong: ["4", "6", "7"] },
      { q: "How many Formula 1 World Championships has Lewis Hamilton won (as of 2024)?", a: "7 (tied with Michael Schumacher)", wrong: ["5", "6", "8"] },
      { q: "In golf, what is one stroke under par on a hole called?", a: "A birdie", wrong: ["An eagle", "A bogey", "An albatross"] },
      { q: "In which country was the sport of cricket invented?", a: "England", wrong: ["India", "Australia", "South Africa"] },
    ],
  },
  {
    title: "Food & Drink",
    description: "Kitchens, cuisines and the bar.",
    questions: [
      { q: "From which country does sushi originate?", a: "Japan", wrong: ["China", "Korea", "Vietnam"] },
      { q: "What type of pastry is used to make a classic profiterole?", a: "Choux pastry", wrong: ["Puff pastry", "Shortcrust", "Filo"] },
      { q: "What is the main ingredient in guacamole?", a: "Avocado", wrong: ["Cucumber", "Lime", "Coriander"] },
      { q: "What is the most widely consumed beverage in the world, after water?", a: "Tea", wrong: ["Coffee", "Beer", "Milk"] },
      { q: "Which spice, by weight, is usually the most expensive in the world?", a: "Saffron", wrong: ["Vanilla", "Cardamom", "Cinnamon"] },
      { q: "What is the primary ingredient in hummus?", a: "Chickpeas", wrong: ["Fava beans", "Lentils", "Soybeans"] },
      { q: "From which country does feta cheese originate?", a: "Greece", wrong: ["Italy", "Turkey", "Bulgaria"] },
      { q: "What does \"al dente\" mean when cooking pasta?", a: "Firm to the bite", wrong: ["Very soft", "Overcooked", "Cold and raw"] },
      { q: "What is the main alcoholic ingredient in a Mojito?", a: "White rum", wrong: ["Vodka", "Tequila", "Gin"] },
      { q: "Which nut is the traditional main ingredient of marzipan?", a: "Almond", wrong: ["Hazelnut", "Walnut", "Pistachio"] },
      { q: "Which country is the birthplace of modern pizza?", a: "Italy", wrong: ["Greece", "France", "United States"] },
      { q: "What is the Japanese word for eel, used for a type of sushi?", a: "Unagi", wrong: ["Maguro", "Sake", "Tako"] },
      { q: "Champagne can only be called Champagne if it is produced in which region?", a: "Champagne, France", wrong: ["Burgundy", "Tuscany", "Catalonia"] },
      { q: "Alongside Campari, what are the two main ingredients in a Negroni?", a: "Gin and sweet vermouth", wrong: ["Vodka and tonic", "Whiskey and soda", "Rum and cola"] },
    ],
  },
];
