// Question banks for the pub quiz. Each round a random 5 questions are drawn
// from the topic's bank so no two quizzes play the same.
// The "Player Round" is built at runtime from questions the players type in.
const GENERAL_ROUNDS = [
  {
    title: "Geography",
    description: "Places, capitals and landmarks.",
    questions: [
      { q: "What is the capital of Australia?", a: "Canberra" },
      { q: "Which country has the largest population in the world?", a: "India" },
      { q: "In which mountain range would you find Mount Everest?", a: "The Himalayas" },
      { q: "Which African country was formerly known as Abyssinia?", a: "Ethiopia" },
      { q: "Which is the only sea on Earth with no coastline?", a: "The Sargasso Sea" },
      { q: "What is the smallest country in the world by area?", a: "Vatican City" },
      { q: "Which river flows through Paris?", a: "The Seine" },
      { q: "On which continent is the Atacama Desert located?", a: "South America" },
      { q: "Which ocean is the deepest?", a: "The Pacific Ocean" },
      { q: "What is the capital of Canada?", a: "Ottawa" },
      { q: "Which country is home to the ancient city of Petra?", a: "Jordan" },
      { q: "The Strait of Gibraltar separates Europe from which continent?", a: "Africa" },
      { q: "Which is the largest country in the world by area?", a: "Russia" },
      { q: "What is the longest river in South America?", a: "The Amazon" },
    ],
  },
  {
    title: "Science & Nature",
    description: "A little bit of biology, chemistry and physics.",
    questions: [
      { q: "What is the chemical symbol for gold?", a: "Au" },
      { q: "How many bones are in the adult human body?", a: "206" },
      { q: "Which planet in our solar system is known as the Red Planet?", a: "Mars" },
      { q: "What is the hardest naturally occurring substance on Earth?", a: "Diamond" },
      { q: "What gas do plants primarily absorb for photosynthesis?", a: "Carbon dioxide (CO₂)" },
      { q: "What is the largest organ of the human body?", a: "The skin" },
      { q: "Which element has the atomic number 1?", a: "Hydrogen" },
      { q: "Which blood type is known as the universal donor?", a: "O negative" },
      { q: "What does DNA stand for?", a: "Deoxyribonucleic acid" },
      { q: "How many hearts does an octopus have?", a: "Three" },
      { q: "What force pulls objects toward the centre of the Earth?", a: "Gravity" },
      { q: "What is the boiling point of water at sea level in Celsius?", a: "100 °C" },
      { q: "What is the speed of light in a vacuum (to the nearest 1,000 km/s)?", a: "About 300,000 km/s" },
      { q: "Which vitamin is produced by the body when exposed to sunlight?", a: "Vitamin D" },
    ],
  },
  {
    title: "History",
    description: "Events and people from the past.",
    questions: [
      { q: "In what year did World War II end?", a: "1945" },
      { q: "Who was the first President of the United States?", a: "George Washington" },
      { q: "The Great Wall of China was primarily expanded under which dynasty?", a: "The Ming dynasty" },
      { q: "Who painted the Mona Lisa?", a: "Leonardo da Vinci" },
      { q: "In which year did the Berlin Wall fall?", a: "1989" },
      { q: "Who was the first woman to win a Nobel Prize?", a: "Marie Curie" },
      { q: "Which civilization built Machu Picchu?", a: "The Inca" },
      { q: "Who wrote the play \"Romeo and Juliet\"?", a: "William Shakespeare" },
      { q: "In what year did the Titanic sink?", a: "1912" },
      { q: "Which British Prime Minister was known as the \"Iron Lady\"?", a: "Margaret Thatcher" },
      { q: "Which empire was led by Julius Caesar?", a: "The Roman Empire" },
      { q: "Which country gifted the Statue of Liberty to the United States?", a: "France" },
      { q: "Who was the first man to walk on the Moon?", a: "Neil Armstrong" },
      { q: "In what year did the French Revolution begin?", a: "1789" },
    ],
  },
  {
    title: "Entertainment",
    description: "Films, music, TV and books.",
    questions: [
      { q: "Who wrote the Harry Potter book series?", a: "J. K. Rowling" },
      { q: "Which band released the 1969 album \"Abbey Road\"?", a: "The Beatles" },
      { q: "Who directed the original 1993 film \"Jurassic Park\"?", a: "Steven Spielberg" },
      { q: "In which TV series would you hear the phrase \"Winter is coming\"?", a: "Game of Thrones" },
      { q: "Which Disney film features a snowman named Olaf?", a: "Frozen" },
      { q: "Who played Jack in the 1997 film \"Titanic\"?", a: "Leonardo DiCaprio" },
      { q: "Which musical features the song \"Defying Gravity\"?", a: "Wicked" },
      { q: "What is the name of the wizarding school in Harry Potter?", a: "Hogwarts" },
      { q: "Who wrote \"The Lord of the Rings\"?", a: "J. R. R. Tolkien" },
      { q: "Which film won Best Picture at the 2020 Oscars?", a: "Parasite" },
      { q: "Which artist painted \"The Starry Night\"?", a: "Vincent van Gogh" },
      { q: "What instrument did jazz legend Miles Davis play?", a: "Trumpet" },
      { q: "Who is the author of the James Bond novels?", a: "Ian Fleming" },
      { q: "What colour pill does Neo take in \"The Matrix\"?", a: "Red" },
    ],
  },
  {
    title: "Sports",
    description: "Teams, rules and record breakers.",
    questions: [
      { q: "How many players from one team are on the pitch in a standard football (soccer) match?", a: "11" },
      { q: "In which sport would you use a shuttlecock?", a: "Badminton" },
      { q: "Which country has won the most FIFA World Cups?", a: "Brazil (5)" },
      { q: "What is the national sport of Japan?", a: "Sumo wrestling" },
      { q: "In tennis, what is a score of zero called?", a: "Love" },
      { q: "How many rings are on the Olympic flag?", a: "Five" },
      { q: "In which sport is the Stanley Cup awarded?", a: "Ice hockey" },
      { q: "How often are the Summer Olympic Games held?", a: "Every four years" },
      { q: "What is the maximum score possible in a single game of ten-pin bowling?", a: "300" },
      { q: "In which city were the 2016 Summer Olympics held?", a: "Rio de Janeiro" },
      { q: "How many players from one team are on a basketball court during play?", a: "5" },
      { q: "How many Formula 1 World Championships has Lewis Hamilton won (as of 2024)?", a: "7 (tied with Michael Schumacher)" },
      { q: "In golf, what is one stroke under par on a hole called?", a: "A birdie" },
      { q: "Which country invented the sport of cricket?", a: "England" },
    ],
  },
  {
    title: "Food & Drink",
    description: "Kitchens, cuisines and the bar.",
    questions: [
      { q: "From which country does sushi originate?", a: "Japan" },
      { q: "What type of pastry is used to make a classic profiterole?", a: "Choux pastry" },
      { q: "What is the main ingredient in guacamole?", a: "Avocado" },
      { q: "What is the most widely consumed beverage in the world, after water?", a: "Tea" },
      { q: "Which spice, by weight, is usually the most expensive in the world?", a: "Saffron" },
      { q: "What is the primary ingredient in hummus?", a: "Chickpeas" },
      { q: "From which country does feta cheese originate?", a: "Greece" },
      { q: "What does \"al dente\" mean when cooking pasta?", a: "Firm to the bite" },
      { q: "What is the main alcoholic ingredient in a Mojito?", a: "White rum" },
      { q: "Which nut is the traditional main ingredient of marzipan?", a: "Almond" },
      { q: "Which country is credited as the birthplace of modern pizza?", a: "Italy" },
      { q: "What is the Japanese word for eel, used for a type of sushi?", a: "Unagi" },
      { q: "Champagne can only be called Champagne if it is produced in which region?", a: "Champagne, France" },
      { q: "What are the two main ingredients in a Negroni, alongside Campari?", a: "Gin and sweet vermouth" },
    ],
  },
];
